INITIAL_JOB_STATUS = "Queued"
JOB_STARTED = "Starting"
JOB_USER_CODE_RUNNING = "In Progress"
JOB_USER_INSTALLING_REQUIREMENTS = "Installing Requirements"
JOB_CANCELLED_BY_USER = "Cancelled"
JOB_DONE = "Done"
JOB_FAILED = "Failed"

ACTIVE_JOB_STATES = [INITIAL_JOB_STATUS, JOB_STARTED, JOB_USER_CODE_RUNNING, JOB_USER_INSTALLING_REQUIREMENTS]
JOB_END_STATES = [JOB_CANCELLED_BY_USER, JOB_DONE, JOB_FAILED]
JOB_STATES = [INITIAL_JOB_STATUS, JOB_STARTED, JOB_USER_CODE_RUNNING, JOB_DONE, JOB_CANCELLED_BY_USER, JOB_FAILED]