
JOB_STATUS_QUEUED = "Queued"
JOB_STATUS_STARTED = "Starting"
JOB_STATUS_RUNNING_COMPUTE = "Running Compute"
JOB_STATUS_INSTALLING_REQUIREMENTS = "Installing Requirements"
JOB_STATUS_CANCELLED = "Cancelled"
JOB_STATUS_DONE = "Done"
JOB_STATUS_FAILED = "Failed"

# JOB_STATUS_UNKNOWN is not in JOB_STATUSES_ACTIVE / JOB_STATUSES_END / JOB_STATUSES
JOB_STATUS_UNKNOWN = "UNKNOWN STATUS"

JOB_STATUS_INITIAL = JOB_STATUS_QUEUED
JOB_STATUSES_ACTIVE = [
    JOB_STATUS_QUEUED,
    JOB_STATUS_STARTED,
    JOB_STATUS_RUNNING_COMPUTE,
    JOB_STATUS_INSTALLING_REQUIREMENTS
]
JOB_STATUSES_END = [
    JOB_STATUS_CANCELLED,
    JOB_STATUS_DONE,
    JOB_STATUS_FAILED
]
JOB_STATUSES = JOB_STATUSES_ACTIVE + JOB_STATUSES_END
