HYPERPLANE_PAT_CATEGORY = "Hyperplane.Access.Tokens"
TOOLS_AND_SERVICES_CATEGORY = "Tools.and.Services"
DATA_SOURCES_AND_TARGETS_CATEGORY = "Data.Sources.and.Targets"
DEFAULT_CATEGORY = TOOLS_AND_SERVICES_CATEGORY


ALL_CATEGORIES = [
    HYPERPLANE_PAT_CATEGORY,
    TOOLS_AND_SERVICES_CATEGORY,
    DATA_SOURCES_AND_TARGETS_CATEGORY,
]